### ISSUE TITLE
Agenda broken release

### ISSUE THREAD

**Issue by ezequieltejada** [vbuzzano/sails-hook-jobs#10]
Hello, I've tried using your library, but I'm getting this error:
```

...\node_modules\sails-hook-jobs\node_modules\agenda\lib\agenda.
js:455
  this._collection.updateMany({_id: { $in: jobIds } }, { $set: { lockedAt: null } }, done);    // NF refactor
ed .update() 22/04/2015
                  ^

TypeError: Cannot read property 'updateMany' of undefined
```
Searching around I've found there are people talking and workaround this: https://github.com/rschmukler/agenda/issues/213

Is it possible to make the same workaround for this library?

Thanks!!!

**Comment by vbuzzano** [comment]
Hi,

Thank you for the feedback.

I have published a new version 0.1.6 . This version has all dependencies updated and the new way to init agenda.

Try it and tell me if it's fix your problem.

**Comment by ezequieltejada** [comment]
I just updated to the 0.1.6 version and I'm getting the exact same error.

I tried deleting the node_modules folder and running another "npm install" to make sure the only version on the folder is the latest.

Also, I made sure that the agenda package is on its latest version too.

I don't know, what's wrong exactly.

Edit:

It seems the problem is here:

```
// Refactored to Agenda method. NF 22/04/2015
// @caller Agenda.stop() only. Could be moved into stop(). NF
Agenda.prototype._unlockJobs = function(done) {
  var jobIds = this._lockedJobs.map(function (job) {
    return job.attrs._id;
  });
  this._collection.updateMany({_id: { $in: jobIds } }, { $set: { lockedAt: null } }, done);    // NF refactored .update() 22/04/2015
};
```

Maybe the scope of "this" is incorrect, but I don't know how to solve it.

**Comment by ezequieltejada** [comment]
It seems that the model I've been using was referencing the old connection. Now I'm having another issue, this doesn't to appear anymore.
