### ISSUE TITLE
Purging jobs missing?

### ISSUE THREAD

**Issue by diegoaguilar** [vbuzzano/sails-hook-jobs#4]
I need to schedule some not repetitive tasks but for a certain date. I got a Mongo database instance at server and a sails application. However I will have a quite large demand in application (up to 100 000 users).

I wonder how this _purging jobs_ as a problem to solve may complicate things in this application.

**Comment by vbuzzano** [comment]
The problem is that you will have lot of old job in mongodb. We should find a way to clean that on sails shutdown. I did not have lot of time to investigate.
