### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by KirillSuhodolov** [vbuzzano/sails-hook-jobs#5]
What is project current status?

**Comment by vbuzzano** [comment]
This hook is just working.. the only problem is that I should take time or find a solution to clean the database on shutdown.

**Comment by KirillSuhodolov** [comment]
@vbuzzano why https://github.com/rschmukler/agenda as backend? and not https://github.com/Automattic/kue for instance?

**Comment by vbuzzano** [comment]
I was looking to use mongodb as nosql backend and Agenda use it. Kue use redis.

**Comment by KirillSuhodolov** [comment]
Only this reason? I am choosing between them, my stack is Postgres and Redis, and I totally don't want add mongo, except if agenda has serious advantages
