### ISSUE TITLE
compatibilty fix for waterline save() update

### ISSUE THREAD

**Issue by jonscyriac** [vbuzzano/sails-hook-jobs#8]
in agenda/job.js, the save() is not compatible with waterline update 0.12.2

**Comment by vbuzzano** [comment]
HI ! where is the file agenda/job.js in the project sails-hook-jobs ?

**Comment by jonscyriac** [comment]
sorry, i was mentioning about the agenda/lib/job.js.

**Comment by vbuzzano** [comment]
Can you tell me how to produce this bug ?

By the way, I have published a new version for the hook for sails 0.12.3
